### ISSUE TITLE
끝말잇기

### ISSUE THREAD

**Issue by pmh-only** [pmh-only/issue#1]
깃헙으로 끝말잇기 할껀데요

**Comment by pmh-only** [comment]
첫단어 추천받음

**Comment by 1-EXON** [comment]
사랑 어떱니까?

**Comment by pmh-only** [comment]
낭만

**Comment by KataLin177** [comment]
만테냐 (이탈리아 화가)

**Comment by pmh-only** [comment]
냐짱 (베트남 항구도시)

**Comment by KataLin177** [comment]
짱포컹 (중국 광둥성 윈푸에 위치한 풍경구)

**Comment by pmh-only** [comment]
컹컹대다

**Comment by potato179** [comment]
다다이즘

**Comment by 1-EXON** [comment]
즘게

**Comment by noeulnight** [comment]
게비스콘

**Comment by csnewcs** [comment]
콘아이스크림

**Comment by pmh-only** [comment]
림월드

**Comment by potato179** [comment]
드라이아이스

**Comment by 1-EXON** [comment]
스리랑카

**Comment by comjun04** [comment]
카네이션

**Comment by noeulnight** [comment]
션크림

**Comment by comjun04** [comment]
> 션크림
> 

@noeulnight 그 단어 있는거 맞아요?

**Comment by noeulnight** [comment]
> 
> 
> > 션크림
> 
> @noeulnight 그 단어 있는거 맞아요?

그러게요

**Comment by potato179** [comment]
> > > 션크림
> > 
> > 
> > @noeulnight 그 단어 있는거 맞아요?
> 
> 그러게요

션크림이 뭐죠 먹는건가요?

**Comment by potato179** [comment]
> 카네이션

션믈

**Comment by noamboy2006** [comment]
믈라카

**Comment by pmh-only** [comment]
카놀라

**Comment by gangjun06** [comment]
라면

**Comment by pmh-only** [comment]
면접

**Comment by noamboy2006** [comment]
접점이 주어진 경우
곡선 y=f(x)
위  (a, f(a))
에서의 접선의 방정식은
y−f(a)=f′(a)(x−a)
이다

**Comment by pmh-only** [comment]
다트

**Comment by 1-EXON** [comment]
트리

**Comment by gangjun06** [comment]
리본

**Comment by csnewcs** [comment]
본디

**Comment by pmh-only** [comment]
디트로이트

**Comment by potato179** [comment]
트리튬

**Comment by noamboy2006** [comment]
튬스톤

**Comment by potato179** [comment]
> 튬스톤

튬스톤이 뭐죠 먹는건가요?

**Comment by Fireworks1205** [comment]
> > 튬스톤
> 
> 튬스톤이 뭐죠 먹는건가요?

요트 타는 사람을 바라보는 나트륨(?)

**Comment by pmh-only** [comment]
톤 매핑

**Comment by 1-EXON** [comment]
핑크

**Comment by Fireworks1205** [comment]
크로스 피닝

**Comment by JIA4224** [comment]
닝샤후이족자치구

**Comment by jwkim101201** [comment]
구리

**Comment by 1-EXON** [comment]
이리듐

**Comment by kimyui76** [comment]
듐한방단어ㅅㅂ

**Comment by pmh-only** [comment]
------------

**Comment by pmh-only** [comment]
나무위키

**Comment by kimyui76** [comment]
키위새

**Comment by jwkim101201** [comment]
새장

**Comment by NamuTree0345** [comment]
장터

**Comment by pmh-only** [comment]
터전

**Comment by gangjun06** [comment]
전장

**Comment by jwkim101201** [comment]
장주릅

**Comment by noamboy2006** [comment]
읍내

**Comment by Fireworks1205** [comment]
내꺼

**Comment by pmh-only** [comment]
꺼림직

**Comment by noeulnight** [comment]
직소

**Comment by csnewcs** [comment]
# 소리소문

**Comment by pmh-only** [comment]
# 문장

**Comment by kimyui76** [comment]
장문

**Comment by noamboy2006** [comment]
문재인(한국 한자: 文在寅, 1953년 1월 24일 ~ )은 대한민국의 제19대 대통령이다. 본관은 남평(南平)이다.[3]

경희대학교 재학 시절 학생운동을 이끌며 박정희 유신 체제에 항거하다가 1975년 서대문구치소에 투옥됐고 대학에서 제적당했다. 출소 후에는 신체 검사도 받지 않은 상태로 군에 강제 징집되었다. 특전사로 군복무를 마친 후 복학해 다시 학생운동을 이끌며 전두환 군부 독재에 항거하다가 1980년 청량리구치소에 투옥됐으나, 조영식 경희대 총장의 신원보증으로 옥중에서 사법시험에 합격하며 극적으로 석방되었다. 1982년 사법연수원을 최우수 성적[4]으로 수료했으나 학생운동 전력으로 판사 임용이 거부되자 부산에서 노무현 변호사와 합동법률사무소를 운영하며 인권변호사로 활동했다.

2003년에 참여정부의 초대 대통령비서실 민정수석을 역임했다. 2004년, 자리에서 물러나 히말라야 산맥으로 트래킹을 떠났으나, 도중에 노무현의 탄핵 소추 소식을 듣고 즉시 귀국하여 변호인단의 간사를 맡았다.[5] 2005년 다시 청와대에 들어가 대통령비서실 시민사회수석, 민정수석, 정무특보를 거쳐 참여정부 마지막 대통령비서실장을 지냈다.

문재인은 2012년 제19대 총선에서 부산 사상구에 출마하여 당선되면서 본격적으로 선출직 정치활동을 시작했다. 동년 대선 출마를 선언했으며 손학규, 김두관, 정세균 등과 겨루어 전국 순회경선 13회 전승을 거두며 민주통합당 제18대 대선 후보로 확정되어 출마하였으나 새누리당의 박근혜 후보에게 패배하였다. 2015년 2월 8일에 새정치민주연합 대표에 선출되었고, 2016년 1월까지 새로 개편된 더불어민주당 대표를 지냈다. 대표직에서 물러난 후 제20대 총선에 출마하지 않았지만 더불어민주당 소속 후보들을 위해 지원 유세를 다녔다. 2016년 11월 박근혜 대통령 탄핵 국면 시기 상임고문으로 활동했다.[6]

2017년 3월 10일, 박근혜가 대통령직에서 파면되어 조기 대선이 결정되자 대권에 재도전하였고, 이재명, 최성, 안희정과 겨루어 전체 표수의 과반을 얻어 결선투표 없이 2017년 4월 3일 더불어민주당 대선 후보 경선에서 최종 승리하여 더불어민주당 제19대 대선 후보가 되었다.[7] 2017년 5월 9일 치러진 대선에서 41.1%를 득표하여 24%를 득표한 자유한국당 홍준표 후보를 누르고 당선되었으며[8], 대통령이 파면되어 치러진 궐위선거이기 때문에 중앙선거관리위원회 당선인 결정 시간인 2017년 5월 10일 8시 9분 대통령직 인수위원회를 구성하지 않고 바로 제19대 대통령에 취임했다.

출처: 위키백과

**Comment by Fireworks1205** [comment]
과학기술정보통신부장관은 과학기술정책의 수립·총괄·조정·평가, 과학기술의 연구개발·협력·진흥, 과학기술인력 양성, 원자력 연구·개발·생산·이용, 국가정보화 기획·정보보호·정보문화, 방송·통신의 융합·진흥 및 전파관리, 정보통신산업, 우편·우편환 및 우편대체에 관한 사무를 관장한다.
② 과학기술정보통신부에 과학기술혁신사무를 담당하는 본부장 1명을 두되, 본부장은 정무직으로 한다.

**Comment by pmh-only** [comment]
뭐지 여기 왜이래

**Comment by Naesung** [comment]
문장잇기

**Comment by Aletive** [comment]
기체(氣體, 영어: gas)는 물질이 나타내는 네 가지 상 즉, 고체, 액체, 기체, 플라스마 중 하나이다. 고체나 액체에 비해 밀도가 낮고, 일정한 모양과 부피를 갖지 않는다. 
기체는 어떤 모양의 그릇에도 들어가고, 또 그 그릇 안에서 확산하여 그릇 속을 가득 채운다. 또 기체는 고체나 액체에 비해서 대단히 가볍고, 압축하기도 쉽다. 이것은 고체나 액체의 입자가 거의 달라붙어 밀집해 있는 데 비해, 기체는 입자 사이의 거리가 매우 크기 때문이다. 기체를 이루고 있는 입자는 모두 분자이며, 항상 공간 속을 자유롭게 날아다니고 있다. 
샤를의 법칙(문화어: 샬의 법칙) 또는 샤를과 게이뤼삭의 법칙(문화어: 샬과 게이루샤크의 법칙)은 이상 기체의 성질에 관한 법칙이다. 1802년에 루이 조제프 게뤼사크이 처음으로 발표하였는데, 그는 1787년경의 자크 알렉상드르 세사르 샤를의 미발표한 논문을 인용하면서 이 법칙을 샤를의 공으로 돌렸다. 
샤를의 법칙은 온도가 1도씩 낮아질때마다 기체의 부피가 1/273 으로 줄어든다는 내용이다. 
일정한 압력에서 기체의 온도를 높이면 부피가 증가하고 온도를 낮추면 부피가 감소한다.

**Comment by potato179** [comment]
체간, 體幹
(명사 동물학•동물명)
척추동물의 몸 중에서 체지를 제외한 몸의 중추 부분. 머리·목·가슴·배·꼬리의 다섯 부분으로 나뉨.

**Comment by ttakkku** [comment]
눰눰
