### ISSUE TITLE
자스까는 방

### ISSUE THREAD

**Issue by abiriadev** [pmh-only/issue#61]

**Comment by noamboy2006** [comment]
? nodejs 를 install 하는 방일꺼라 믿습니다

**Comment by abiriadev** [comment]
[1, 3, 10].sort()
>[1, 10, 3]

**Comment by abiriadev** [comment]
`1/0`
`\> Infinity`

**Comment by abiriadev** [comment]
자스는 정말....

**Comment by noamboy2006** [comment]
......

**Comment by noamboy2006** [comment]
> `[1, 3, 10].sort()`
> `> [1, 10, 3]`

문자열 기반 sort를 실행시켜놓고 그렇게 말하시니....

**Comment by jwkim101201** [comment]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by Muzihuzi** [comment]
자스는 최고입니다
이런 자스를 모두가 깔아야 합니다

**Comment by aNchor-only** [comment]
와아아

**Comment by abiriadev** [comment]
> > `[1, 3, 10].sort()`
> > `> [1, 10, 3]`
> 
> 문자열 기반 sort를 실행시켜놓고 그렇게 말하시니....

문론 저도 아는데....

문제는 그냥 자스가 상당히 관용적이라 없는 변수가 undefined로 나오는 등 상당히 심각한 언어라 그렇습니다....

님도 TS써보시면 알게 되실걸요

**Comment by pmh-only** [comment]
타스 쓰는사람들은 트리넷에서 퇴출해야 하비단

**Comment by noeulnight** [comment]
> 타스 쓰는사람들은 트리넷에서 퇴출해야 하비단

따꾸 타스 쓰지않?

**Comment by pmh-only** [comment]
나도 쓰는데

**Comment by jwkim101201** [comment]
???????????????

**Comment by noeulnight** [comment]
> 나도 쓰는데

너 나가

**Comment by pmh-only** [comment]
ㄲㅂ

**Comment by abiriadev** [comment]
아니 ㅋㅋㅋ 다들 모르시나 본데

자스가 진짜 개념없는 언어라고 자바나 C#쓰는 개발자들한테 욕 엄청 많이 먹어요 ㅋㅋㅋ

단순히 약타입 언어를 더나서 인터페이스도 없지, 클래스도 없고(생성자 함수라는 게 있다가 나중에 TS영향으로 클래스가 도입되었는데 내부적으론 생성자 함수로 동작하기 때문에 다른 객체지향 언어처럼 static을 쓴다던가, 메서드 오버로딩을 쓴다던가, 인터페이스를 다중상속한다던가 등등의 막강한 기능을 단 1도 사용할 수 없거든요? ㅋㅋㅋ)

결국 그 부실함 때문에 자스가 대규모 프레임워크에 쓰이는 요즘 시대는 정말이지 기적이 아닐 수 없습니다 ㅋㅋㅋ

앵귤러2 만 해도 아예 타스를 통째로 반영하는 걸 보세요.

바닐라 자스는 걀국 상당히 코드 유지보수 및 관리가 심각한 데다가 import문마저 CommonJS랑 ES6방식으로 꼬여서 ㅋㅋㅋ 지금 정말 제가 쓰면서도 참 한숨이 나올 정도입니다 ㅋㅋㅋ

~~어쨌튼 자스는 갓~~

**Comment by abiriadev** [comment]
뭐 애초에 무지무지 쉬운 언어를 만들려고 했으니 이리되는 것도 당연하지만...

애초에 문자열과 숫자를 더할 수 있다는 것만 해도 아주 참신한(?) 생각입니다 ㅋㅋ

**Comment by pmh-only** [comment]
뭐야 저 진지충은

**Comment by pmh-only** [comment]
극혐이네 차단합니다

**Comment by abiriadev** [comment]
으앙

살려주세요

@pmh-only

**Comment by noeulnight** [comment]
bye

**Comment by abiriadev** [comment]
근데 차단해도

깃헙은 차단 안되지 않나요?

**Comment by abiriadev** [comment]
케케케켘ㅋ

**Comment by pmh-only** [comment]
에휴 초딩새끼

**Comment by abiriadev** [comment]
> 에휴 초딩새끼

아니 이건 좀 심하시네요;

**Comment by pmh-only** [comment]
개 극혐이라 볼때마다 욕밖에 안나와서 그렇습니다

**Comment by abiriadev** [comment]
저요?

**Comment by pmh-only** [comment]
그래 너요

**Comment by pmh-only** [comment]
근데 에초에 자스 하는사람이 C#이랑 자바를 못하는 사람이 있긴 함?

**Comment by abiriadev** [comment]
> 개 극혐이라 볼때마다 욕밖에 안나와서 그렇습니다

절 볼때마다 극혐이시라는 건 아니신 거 같은데요....?

**Comment by abiriadev** [comment]
> 근데 에초에 자스 하는사람이 C#이랑 자바를 못하는 사람이 있긴 함?

음....?

많은데요???

**Comment by pmh-only** [comment]
그건 걔내들 문제구요.. 언어 몇개 모르는 사람이 어느 언어가 개같다 그 소리 짓꺼리더라구요

**Comment by abiriadev** [comment]
음,....

자바스크립트 문제 많은건 많이 해보셔서 아시잖아요?

**Comment by abiriadev** [comment]
맨날 undefined로 버그나는거 짜증납니다만.....

**Comment by pmh-only** [comment]
언어를 다양하게 알면 언어마다 장단점이 보이니까 욕을 안하는거고
언어도 잘 모르는 코린이 새끼들이 언어 까대리는건 보기 싫습니다

**Comment by abiriadev** [comment]
음.....

**Comment by abiriadev** [comment]
제가 코린이라니

**Comment by abiriadev** [comment]
나중에 후회하시겠네요

**Comment by pmh-only** [comment]
예 지금도 이런 사람을 만났나 후회하고 있습니다

**Comment by abiriadev** [comment]
네 알아서 하시고요 다시 저한테 말걸지 마세요

**Comment by pmh-only** [comment]
? 님 누구세요?

**Comment by pmh-only** [comment]
첨보는 사람이네

**Comment by pmh-only** [comment]
앗싸 한놈 해결
